import fs from 'node:fs';
const releases=JSON.parse(fs.readFileSync('manifests/releases.json'));
const repo='https://github.com/Touxten/presta-distributions';
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const asset=(r,a)=>`${repo}/releases/download/${r.tag}/${encodeURIComponent(a)}`;
const latest=releases.find(r=>!r.prerelease);
const rows=releases.map(r=>`<tr data-kind="${r.prerelease?'preview':'stable'}" data-version="${esc(r.version)}"><td><strong>${esc(r.version)}</strong><span class="badge ${r.prerelease?'preview':''}">${r.prerelease?'Préversion':'Stable'}</span></td><td class="date">${new Date(r.date+' 12:00:00 UTC').toLocaleDateString('fr-FR',{day:'numeric',month:'short',year:'numeric',timeZone:'UTC'})}</td><td>${(r.assets[0].bytes/1048576).toFixed(1).replace('.',',')} Mo</td><td><a class="download" href="${asset(r,r.assets[0].name)}" aria-label="Télécharger le ZIP ${esc(r.version)}">ZIP <span aria-hidden="true">↗</span></a><a href="${asset(r,r.assets[1].name)}" aria-label="Télécharger le XML ${esc(r.version)}">XML</a><a href="${asset(r,'SHA256SUMS')}" aria-label="Empreintes SHA-256 ${esc(r.version)}">SHA-256</a></td><td><a class="source" href="https://github.com/PrestaShop/PrestaShop/releases/tag/${r.version}">Notes de version ↗</a><a class="commit" href="https://github.com/PrestaShop/PrestaShop/commit/${r.sourceCommit}">${r.sourceCommit.slice(0,8)}</a></td></tr>`).join('\n');
let template=fs.readFileSync('site/template.html','utf8');
template=template.replace('<!-- RELEASE_ROWS -->',rows).replaceAll('{{LATEST}}',latest.version).replaceAll('{{LATEST_ZIP}}',asset(latest,latest.assets[0].name)).replaceAll('{{LATEST_XML}}',asset(latest,latest.assets[1].name));
fs.writeFileSync('site/index.html',template);
console.log('Built static catalogue');
